name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest, self-hosted]
    env:
      PLEASE_PRELOAD_LIBSTDCPP: true

    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
                git \
                curl \
                wget \
                ssh \
                build-essential \
                make \
                cmake \
                ninja-build \
                pkg-config \
                libglib2.0-dev \
                python3 \
                python-is-python3 \
                lsb-release \
                libboost-all-dev
    
    - name: Install clang-13 and other required tools
      run: |
        wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
        echo "deb [signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/jammy/ llvm-toolchain-jammy-13 main" | sudo tee /etc/apt/sources.list.d/llvm-13.list
        sudo apt-get update && sudo apt-get install -y clang-13 lld-13 llvm
    
    - name: Configure with CMake
      run: |
        export CC=clang-13
        export CXX=clang++-13
        cmake -GNinja -S . -B build
    
    - name: Build
      run: cmake --build build

    - name: Conversion Test
      run: ./Test/Applications/x2tTester/conversionTest.sh ./Test/Applications/x2tTester ../../../build/package
